permalink: none
#baseurl:   /Lutra
baseurl: /home/pkv/Desktop/Lutra/_site

# Is this necessary?
#url: file:///home/pkv/Desktop/Lutra/_site

ga_id: 
google_search_api_key: 
google_search_site_url: http://example.com
title_prefix: Platypus Lutra
company_name: Platypus, LLC
